#~/bin/bash

if [ "$#" != "2" ]; then
        echo "Missing Arguments:"
        echo "First Argument: -w or --worker for worker node, -m or --manager for manager node"
        echo "Second Argument: New hostname"
        echo "example to setup as worker with hostname hana05"
        echo "sh node_setup.sh -w hana05"

else
        echo "Begining Setup....."

        #------------------------ UPDATE HOSTNAME --------------------
        # Create Back Up of /etc/hostname and /etc/hosts
        cp /etc/hostname /etc/.hostname
        cp /etc/hosts /etc/.hosts

        echo "Updating /etc/hostname and /etc/hosts with new name: "$2
        # Need to update this to correct filename
        sudo sed -i "s/$(hostname)/$2/" /etc/hostname /etc/hosts

        #------------------ UPDATE AND UPGRADE SYSTEM ----------------
        echo "Checking for updates....."
        sudo apt-get update > /dev/null #> /dev/null to hide standard output
        echo "Applying Updates"
        sudo apt-get upgrade -y > /dev/null #> /dev/null to hide standard output

        #---------------- INSTALL DOCKER -----------------------------
        

        #---------------- ADD CURRENT USER TO DOCKER GROUP -----------


        #---------------AUTOSTART DOCKER SERVICES --------------------


        # ---------------------- JOIN SWARM --------------------------
        # UPDATE THIS PORTION WITH THE COMMANDS GENERATED BY YOUR SWARM
        case "$1" in
            --worker | -w)
                echo "Joining Swarm as Worker"
                # Add WORKER Setup Command Here
                ;;
            --manager | -m)
                echo "Joining Swarm as Manager"
                # Add MANAGER Setup Command Here
                ;;
        esac

        # ------------------ SETUP SYNCTHING --------------------------

        echo "Setup Complete"
fi


exit 0